# Generated by Django 5.0.7 on 2024-07-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('bio', models.TextField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
